spring:
  kafka:
    producer:
#      retries: 3
#      retry-backoff-ms: 500
#      acks: all
#      enable-idempotence: true
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

