spring.application.name=Product-Microservice
server.port=8081
management.endpoints.web.exposure.include=*
spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create
cache.ttl=600
cache.maxSize=1000
spring.redis.host=localhost
spring.redis.port=6379
spring.kafka.bootstrap-servers=localhost:9092







